### ISSUE TITLE
1.5 install failed

### ISSUE THREAD

**Issue by S0und** [google/android-emulator-hypervisor-driver-for-amd-processors#12]
> [SC] ControlService FAILED 1062:
> 
> The service has not been started.
> 
> [SC] DeleteService SUCCESS
> [SC] StartService FAILED with error 4294967201.
> 

I'm already using the driver (1.4) on my desktop 3700X, but installing 1.5 manually failed.

**Comment by xJon** [comment]
I had `1.4` already installed, and I installed 1.5 manually after Android Studio downloaded it and got `STATE : 4 RUNNING`. (using Ryzen 3600).

**Comment by Taogle2018** [comment]
The error code is misleading because it is a Linux one (a negative integer is interpreted as a very big unsigned value).
It means that either virtualization is not enabled in BIOS or other hypervisors are blocking (typically Hyper-V).
Can you verify 1> virtualization is enabled in BIOS; and 2> Hyper-V is NOT enabled?

**Comment by McSken** [comment]
> The error code is misleading because it is a Linux one (a negative integer is interpreted as a very big unsigned value).
> It means that either virtualization is not enabled in BIOS or other hypervisors are blocking (typically Hyper-V).
> Can you verify 1> virtualization is enabled in BIOS; and 2> Hyper-V is NOT enabled?

I verified both and I still get the error :/ anything else I could try?

**Comment by S0und** [comment]
https://i.imgur.com/BhPStCk.png

**Comment by Taogle2018** [comment]
> > The error code is misleading because it is a Linux one (a negative integer is interpreted as a very big unsigned value).
> > It means that either virtualization is not enabled in BIOS or other hypervisors are blocking (typically Hyper-V).
> > Can you verify 1> virtualization is enabled in BIOS; and 2> Hyper-V is NOT enabled?
> 
> I verified both and I still get the error :/ anything else I could try?
> 
> Update:
> Fixed it after attempting a few things. I think what fixed it was updating Android SKD Build-Tools 30-rc4 under SDK tools, it needed an update and I didnt notice. ¯_(ツ)_/¯

The driver has no relation to Android SDK Build Tools. I do wonder why this can be the cause.

**Comment by Taogle2018** [comment]
> https://i.imgur.com/BhPStCk.png

Can you download and run the following program in commandline?
https://1drv.ms/u/s!AljlID0ntVyugeRkxOXscgdtZVCWOQ?e=dVx1S2

This is a very simple CPUID program I used to detect Hyper-V. You can disassemble it and see if this is safe enough for you to run (Sometime antivirus program will block). Its size is bigger than what one would expect for binaries from a few lines of codes because I choose to statically link the c runtime.

**Comment by S0und** [comment]
@Taogle2018 

```
Hypervisor feature flag 80000000
Hypervisor string Microsoft Hv
Hypervisor signature Hv#1
```

**Comment by Taogle2018** [comment]
This means on your system Hyper-V is turned on. Checking feature checkbox in "Turn on and off Windows features" is not reliable at all. Sometime it is enabled implicitly by other Microsoft features.
However, I cannot tell you what it is. Known possibilities are "Windows Sandbox", "Virtual Machine Platform", "Credential Guard", "Core Isolation" (in Windows Defender options).

**Comment by Taogle2018** [comment]
If your PC is issued by an organization, please do contact your IT department. There might be security features enabled that eventually enabled Hyper-V (without letting user know).

**Comment by S0und** [comment]
As i mentioned before, i already have 1.4, so at one point in time, i was able to install it without issue.

That's true that i had Windows Sandbox enabled, but even after disabling i had HV on. 

* Virtual Machine Platform is also off
* Credential Guard is off, i guess?! https://i.imgur.com/8NUcJj5.png
* Core Isolation: i'm not sure about this, Windows Security -> Device security -> "Core isolation" has a green checkmark on the icon, but inside the "Core isolation details" "Memory integrity" is off

**Comment by Taogle2018** [comment]
I had similar experience with you. I cannot disabled HV after I enable it. However, sometime "system restore" can revert the changes which disabled HV. You can have a try.
It is more of Microsoft bug. Sorry, I cannot do anything in this case.

**Comment by Taogle2018** [comment]
I think Credential Guard should be off. I Normally corporate IT would enable it but not end users.

**Comment by Sooraj-s-98** [comment]
same problem
