### ISSUE TITLE
Can't find gvm.sys when use "gvm.inf"

### ISSUE THREAD

**Issue by noormanyulizarp** [google/android-emulator-hypervisor-driver-for-amd-processors#16]
When run "gvm.inf" it seems can't find the gvm.sys so the install was stuck on step for locate the gvm.sys

**Comment by Taogle2018** [comment]
I do not quite understand. What do you mean by running "gvm.inf"?

**Comment by noormanyulizarp** [comment]
so i can't find the "silent_install script" then try to run gvm.inf "by right click then install, as you mentioned here:

[ I believe the problem is probably caused by the vbscript for detecting and asking admin privilege. There is another way to install the driver. Right click "gvm.inf" and choose install. Once done, use "sc query gvm" to check whether the driver is up and running. If not, use "sc start gvm" to start the driver. ]

but it still won't installed because missing "gvm.sys"

**Comment by Taogle2018** [comment]
Probably they are deleted by your antivirus program?

**Comment by Taogle2018** [comment]
#21 The user confirmed that the missing file is deleted by antivirus program. So let me close the issue. Feel free to reopen it if you need.
