### ISSUE TITLE
Possible to use this with Hyper-V enabled?

### ISSUE THREAD

**Issue by shabbirh** [google/android-emulator-hypervisor-driver-for-amd-processors#18]
I'm unable to install this emulator since I already have Docker installed and as a result, have Hyper-V enabled?  (I'm running on Windows 10 Pro (1909 x64).

Thanks

**Comment by Taogle2018** [comment]
No. Hyper-V is a type-1 hypervisor that blocks other hypervisor including android emulator hypervisor driver.
You may see that VMWare and VirtualBox can run with Hyper-V. I believe they are simply adopting Windows Hypervisor Platform (which is still Hyper-V based).
In your case, if you have to live with Hyper-V, you should be able to use Android Emulator with Windows Hypervisor Platform.
