### ISSUE TITLE
Can not be used in conjunction with VirtualBox

### ISSUE THREAD

**Issue by codemasterover9000** [google/android-emulator-hypervisor-driver-for-amd-processors#2]
Hi,

When starting the Android Emulator. I noticed my VirtualBox crashing. The virtual machines get into a "Guru meditation" state. The cause seems to be that the Android Emulator is locking the AMD hypervisor at which point VirtualBox has no access anymore. The following line appears in the VirtualBox virtual machine logs.

```00:05:22.387523 emR3Debug: rc=VERR_SVM_IN_USE```

Running in Windows 10 using an AMD 3700X.

**Comment by Taogle2018** [comment]
Thanks for reporting. I will take a look.
Judging from the error message itself, it seems virtualbox likes to turn on virtualization extension by themselves (not to continue running even other party turns on the virtualization extension already). I believe there is no locking but we leave HW in a state that Virtualbox does not like and would not cooperate with.

**Comment by Taogle2018** [comment]
I've reproduced the issue, working on a fix.

**Comment by Taogle2018** [comment]
Fixed in v1.3. It will take some time to release from Android Studio. You can download from github if you like.

**Comment by codemasterover9000** [comment]
Thanks for the quick response! Just tested it. Works perfectly.

**Comment by Taogle2018** [comment]
You are welcome! Thanks for reporting issues to us.
