### ISSUE TITLE
Unable to locate 'silent_install.bat'

### ISSUE THREAD

**Issue by James74351595** [google/android-emulator-hypervisor-driver-for-amd-processors#21]
Android Studio gives me an error directing me to this repo for a manual install. I have downloaded this and it is in the correct directory but I cannot locate a 'silent_install.bat' to install it and I also cannot see one here in the repo...

Any help would be appreciated

**Comment by Taogle2018** [comment]
https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/issues/16
It looks like the same issue. 
Did your antivirus program delete these files?

**Comment by James74351595** [comment]
I don't think so as I cannot see the files in the Github repo on the internet and if I open the zip file with WinRar I also cannot find them

**Comment by Taogle2018** [comment]
Downloaded from here? https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/releases/download/v1.5/gvm-windows_v1_5_0.zip
I just double checked and the zip file is OK.
When you downloading, some antivirus program will monitor the files inside a zip package and delete those they think harmful (and leave others untouched).
If only "silent_install.bat" and "gvm.sys" is deleted, I think it is very likely an antivirus program is blocking. What files do you have in the zip? If those two were deleted, the remaining should be "gvm.cat", "gvm.inf" and "README.txt".
Be noted: An antivirus program may not appear in your pc but network gateways.

**Comment by James74351595** [comment]
Thanks! The link you provided worked after I disabled by antivirus, just got the virtual machine working. :)
