### ISSUE TITLE
BSOD: gvm.sys failing when 2 emulator are opened at once

### ISSUE THREAD

**Issue by Rc85** [google/android-emulator-hypervisor-driver-for-amd-processors#23]
I was developing a react native app using one emulator and never encountered this issue. After I added another emulator to my AVD manager and run my app on that emulator as well, I am getting BSOD.

Both emulator are listening on port 8081 and have port tcp:80 reversed using `adb -s [emulator name] reverse tcp:80 tpc:80`.
Whenever I save my code and the emulator refreshes or if I go to refresh the emulators manually, occasionally, I would get BSOD with stop code `SERVICE_SERVICE_EXCEPTION` and `gvm.sys fail`. Below is the crash dump information.

```
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

SYSTEM_SERVICE_EXCEPTION (3b)
An exception happened while executing a system service routine.
Arguments:
Arg1: 00000000c0000005, Exception code that caused the bugcheck
Arg2: fffff806361b1007, Address of the instruction which caused the bugcheck
Arg3: ffffa6078654eb80, Address of the context record for the exception that caused the bugcheck
Arg4: 0000000000000000, zero.

Debugging Details:
------------------

*** WARNING: Unable to verify timestamp for gvm.sys

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 1

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on DESKTOP-BSVEGTG

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 7

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 78

    Key  : Analysis.System
    Value: CreateObject


DUMP_FILE_ATTRIBUTES: 0x8
  Kernel Generated Triage Dump

BUGCHECK_CODE:  3b

BUGCHECK_P1: c0000005

BUGCHECK_P2: fffff806361b1007

BUGCHECK_P3: ffffa6078654eb80

BUGCHECK_P4: 0

CONTEXT:  ffffa6078654eb80 -- (.cxr 0xffffa6078654eb80)
rax=000000000000369c rbx=0000000000000781 rcx=ffffc40a11000000
rdx=0000000000000000 rsi=ffffc40a2c487740 rdi=ffffc40a2c567000
rip=fffff806361b1007 rsp=ffffa6078654f570 rbp=000000000006f200
 r8=ffffa40000000000  r9=0a0000000369cb63 r10=ffffa4620517a130
r11=ffffa45229148000 r12=0000000000000001 r13=0000000000000000
r14=0000000000000000 r15=0000000000000200
iopl=0         nv up ei pl nz ac po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010216
gvm+0x11007:
fffff806`361b1007 48897210        mov     qword ptr [rdx+10h],rsi ds:002b:00000000`00000010=????????????????
Resetting default scope

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  qemu-system-x8

STACK_TEXT:  
ffffa607`8654f570 ffffa462`050f2da8 : ffffa452`00000001 00000000`0369c000 ffffa452`29148c40 ffffa607`8654f590 : gvm+0x11007
ffffa607`8654f578 ffffa452`00000001 : 00000000`0369c000 ffffa452`29148c40 ffffa607`8654f590 ffffa607`8654f590 : 0xffffa462`050f2da8
ffffa607`8654f580 00000000`0369c000 : ffffa452`29148c40 ffffa607`8654f590 ffffa607`8654f590 00000000`0006f34b : 0xffffa452`00000001
ffffa607`8654f588 ffffa452`29148c40 : ffffa607`8654f590 ffffa607`8654f590 00000000`0006f34b 00000000`00000001 : 0x369c000
ffffa607`8654f590 ffffa607`8654f590 : ffffa607`8654f590 00000000`0006f34b 00000000`00000001 00000000`00000002 : 0xffffa452`29148c40
ffffa607`8654f598 ffffa607`8654f590 : 00000000`0006f34b 00000000`00000001 00000000`00000002 00000000`00000001 : 0xffffa607`8654f590
ffffa607`8654f5a0 00000000`0006f34b : 00000000`00000001 00000000`00000002 00000000`00000001 ffffc40a`0c631bc8 : 0xffffa607`8654f590
ffffa607`8654f5a8 00000000`00000001 : 00000000`00000002 00000000`00000001 ffffc40a`0c631bc8 fffff806`361af5da : 0x6f34b
ffffa607`8654f5b0 00000000`00000002 : 00000000`00000001 ffffc40a`0c631bc8 fffff806`361af5da ffffc40a`2c567000 : 0x1
ffffa607`8654f5b8 00000000`00000001 : ffffc40a`0c631bc8 fffff806`361af5da ffffc40a`2c567000 00000000`00000002 : 0x2
ffffa607`8654f5c0 ffffc40a`0c631bc8 : fffff806`361af5da ffffc40a`2c567000 00000000`00000002 00000000`00000000 : 0x1
ffffa607`8654f5c8 fffff806`361af5da : ffffc40a`2c567000 00000000`00000002 00000000`00000000 ffffc40a`2c567000 : 0xffffc40a`0c631bc8
ffffa607`8654f5d0 ffffc40a`2c567000 : 00000000`00000002 00000000`00000000 ffffc40a`2c567000 00000000`00000001 : gvm+0xf5da
ffffa607`8654f5d8 00000000`00000002 : 00000000`00000000 ffffc40a`2c567000 00000000`00000001 fffff806`00000007 : 0xffffc40a`2c567000
ffffa607`8654f5e0 00000000`00000000 : ffffc40a`2c567000 00000000`00000001 fffff806`00000007 00000000`00547810 : 0x2


SYMBOL_NAME:  gvm+11007

MODULE_NAME: gvm

IMAGE_NAME:  gvm.sys

STACK_COMMAND:  .cxr 0xffffa6078654eb80 ; kb

BUCKET_ID_FUNC_OFFSET:  11007

FAILURE_BUCKET_ID:  0x3B_c0000005_gvm!unknown_function

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {7df1ea28-030e-b139-03b7-de07a2c5c1a4}

Followup:     MachineOwner
---------
```
Any help would be appreciated.

**Comment by Taogle2018** [comment]
Can you upload the crash dump so that I can take a look?

**Comment by Taogle2018** [comment]
https://1drv.ms/u/s!AljlID0ntVyugehHeyCgYHkiJSUAew?e=JekxoT
You can download the symbols here. FYI.

**Comment by Taogle2018** [comment]
I tend to believe this is the same issue as https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/issues/14. I have not been able to reproduce #14. Hope I can reproduce using your method.

**Comment by Rc85** [comment]
Windows auto deleted my minidump files, so give me some time to try to reproduce the issue and I'll send you the files. When I posted this and tried to upload the files to Github, it gave me an error saying it cannot open the file.

**Comment by Taogle2018** [comment]
Thanks for your help.
I am actually not an Android developer myself. So just let me confirm:
---- I need to run command "adb -s emulator-5554 tcp:80 tcp:80" and "adb -s emulator-5556 tcp:80 tcp:80".
I hope I won't need the app to trigger the BSOD.

**Comment by Rc85** [comment]
> Thanks for your help.
> I am actually not an Android developer myself. So just let me confirm:
> ---- I need to run command "adb -s emulator-5554 tcp:80 tcp:80" and "adb -s emulator-5556 tcp:80 tcp:80".
> I hope I won't need the app to trigger the BSOD.

Can't say if you need the app or not.

I got the BSOD again today and the only thing that I did before it happened, was editing my app's AndroidManifest.xml and then proceeding to save one of my component file without rebuilding/running `npm run android`.

I attached the dump file.
[070720-18390-01.zip](https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/files/4887919/070720-18390-01.zip)

**Comment by Taogle2018** [comment]
Thanks for sharing the dump. It is the same issue as #14. I am working on this.

**Comment by fusionneur** [comment]
i got a gvm.sys bsod today, when powering off an x86 (android q) avd by long holding the power button and selecting power off. Not sure if this helps in any way, but i leave this here.

**Comment by Taogle2018** [comment]
https://1drv.ms/u/s!AljlID0ntVyugehxayBpYN3uOnXidw?e=ZQ1cuo
Can you try this driver build and see if it fixes the problem?

**Comment by AndrewMorsillo** [comment]
@Taogle2018 I've run into the blue/greenscreen of death also.  It happens randomly for me, not very frequently, once every few days maybe. Last time the crash corrupted my react-native project and git index, had to clone again and lost hours of work =(

Should I also try the new build?

**Comment by Taogle2018** [comment]
I am sorry for the trouble. Since I did not get any response from @Rc85. I went ahead and release the fix with 1.6. Are you using 1.6 already? If so, your crash would be something else. But if not, you can try 1.6 and see if that fixes the problem.
And if you can share your crashdump, that could be a great help too.

**Comment by Rc85** [comment]
@Taogle2018 I've been using the new build for about a week now but only on one emulator and haven't had a BSOD yet. I'll let you know if it any issue comes  up.

**Comment by AndrewMorsillo** [comment]
@Taogle2018 it looks like 1.6 is not available through Android Studio, is that expected? Should I just download 1.6 and run silent_install.bat? If so how do I confirm the version installed successfully? Thanks

**Comment by Taogle2018** [comment]
You can download the driver here. Releasing via Android Studio has to follow their releasing process, which usually takes extra time. Typically I would go to C:\Windows\system32\drivers\gvm.sys, check its version using file property. You can also use "emulator-check.exe accel".

**Comment by AndrewMorsillo** [comment]
So far 1.6 is stable but I wasn't getting crashes very often. Once every couple days. Will report back if I encounter any more.

**Comment by Taogle2018** [comment]
Thanks!

**Comment by jaaywags** [comment]
I had this exact same issue. I was still on 1.5 too. I was able to update it right through Android Studio, Check for updates. Thanks for the tip!
