### ISSUE TITLE
StartService FAILED with error 4294967201

### ISSUE THREAD

**Issue by adrianriyadi** [google/android-emulator-hypervisor-driver-for-amd-processors#27]
![Virtualization Enabled](https://user-images.githubusercontent.com/24358334/89371566-f436cc00-d70d-11ea-9465-62d11f689a80.png)

AMD Ryzen 7 4700U

![Hyper-V is not installed](https://user-images.githubusercontent.com/24358334/89371618-0fa1d700-d70e-11ea-8a6d-03503cbb8683.png)

Hyper-V disabled already.
I got this error log when I tried to install it using cmd (run as admin already). Android studio showed the same error message

![Screenshot (10)](https://user-images.githubusercontent.com/24358334/89371660-29dbb500-d70e-11ea-911a-13962ab0baf7.png)

**Comment by Taogle2018** [comment]
Thanks for these detailed information. This error code means the driver cannot gain access to CPU's virtualization extension.
Possible  reasons could be:
1> Virtualization extension does not exist or disabled by BIOS.
2> Virtualization extension was occupied by another piece of software.
For reason 2, we typically see Hyper-V. But there could be other software as well. For example, quite a few antivirus programs use virtualization extension.
What is your antivirus program? Can you totally disable the antivirus program and see if this can work?

**Comment by adrianriyadi** [comment]
I solved this problem by change SDK platform from 9.0 to 10. A little bit weird but it works. That's why I closed this issue. Thanks for your help

**Comment by Taogle2018** [comment]
Glad that the problem is gone. But it is weird since this should have no relation with SDK platform.
Anyway, if the problem happens again, you can try to disable Antivirus program and see if it can work.

**Comment by adrianriyadi** [comment]
Yes, I think the same. Really weird, but worth it to try since I was so exhausted when got this problem for around 3 days alone. I disabled my antivirus before, no work at all

**Comment by Taogle2018** [comment]
OK. Another thing that is good to have a try is installing vbox and see if it can work with HW virtualization. Technically, the same thing that blocks this driver should also block vbox. However, vbox supports running with SW virtualization. So it will need to create a dummy VM and check its setting page.
Usually the last thing I would try is to ask for remote access. However, I believe this is too intrusive for quite a lot users.

If you have problems in future, we can always chat here in github.

**Comment by gnsubha** [comment]
I am encountering a similar problem today, as the Android Emulator Hypervisor Driver for AMD Processors is failing to install with the same error code

I am using Ryzen 3 3200G

**Comment by Taogle2018** [comment]
Any screenshots to help me diagnose?

**Comment by gnsubha** [comment]
Hello Shan, Thanks for offering the help. I was trying too many options and I believe a power shell script for (Hyper-V) resolved the issue.

**Comment by y1111** [comment]
got this too . its  for having docker opened

**Comment by grecostyler** [comment]
got the same problem  and already tried to disable antivirus and more.
any further suggestions?

![1dea58b98ae248f103811c94917d906c](https://user-images.githubusercontent.com/23472077/97510673-8b19ca00-1985-11eb-8596-8226e9616571.png)

**Comment by SVD6** [comment]
Got the same issue. New Ryzen 5 5600x.

**Comment by SJang1** [comment]
Got the same issue. StartService FAILED with error 4294967201
Ryzen 5 3600X.
![image](https://user-images.githubusercontent.com/29011440/99647918-c2b3f780-2a95-11eb-9933-d62f18492caa.png)

I've disabled all things about Hyper-V, it still continues.

**Comment by Asedirin1** [comment]
I have same issue "StartService FAILED with error 4294967201." 

Using Ryzen 3600X 

The description for Event ID 7000 from source Service Control Manager cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Android Emulator Hypervisor Driver for AMD Processors Service
%%4294967201

The resource loader failed to find MUI file

**Comment by rjworks** [comment]
help pls!!

**Comment by MichaelMcDonnell** [comment]
Be sure to check your BIOS. On my computer Windows said virtualization was enabled even when it wasn't. I've opened pull request #49 to point this out in the README.

**Comment by codeforyourselff** [comment]
> Got the same issue. New Ryzen 5 5600x.

yes i am facing same issue after disabled hyper-v and memory integrity from windows security.can't install driver for amd

**Comment by theahmadzai** [comment]
Same issue but emulator is working fine and smooth.

**Comment by aajahid** [comment]
> In windows 11, hyper-v is inactive looking at windows features, yet system info showed "a hypervisor has been detected". disabling the 'Virtual Machine Platform' fixes this but kills wsl2.

I'm facing the same issue on windows 11. It's either wsl2 or android emulator! But I need both!
Did you get any solution?

**Comment by yifanHuang129** [comment]
AMD Ryzen 7 4800H faces the same issue. I disabled Hyper-V and enable the virtualization, closed anti-virus, but it still did not work.

**Comment by yifanHuang129** [comment]
I solved the problem by downloading a game-play emulator that allows users to play mobile games on the computer.

**Comment by michalhainc** [comment]
my virtualbox doesnt have any problems running vms yet I get this error from this amd driver :(

**Comment by Vikrant4549** [comment]
> my virtualbox doesnt have any problems running vms yet I get this error from this amd driver :(

Go to BIOS -> enable virtualization, it should work then

**Comment by nannerpusser** [comment]
This seems to be a limitation of either (or both) Android Emulator and Windows 10/11 virtualization. I ran into this same issue with other Hyper-V-based software while using WSL2. It's either lose WSL2 or don't use another virtualized solution like Android Emulator (or a lot of AMD-based Ryzen software).

**Comment by serdox** [comment]
i have wsl disabled and still have this issue. i uninstalled virtual box and vmware. no matter what fix i tried i cant run the android emulator. it asks for android hypervisor to be installed and when i cancel it wont start. if i try to install i get error. same as here.  played around with windows features on and off. still not working. im lost. android studio has always been an horrible experience for me. now i need it again and look. unfix-able bug again.
