### ISSUE TITLE
DeleteService ERROR 1072 / StarService ERROR 1058

### ISSUE THREAD

**Issue by denislfernandez** [google/android-emulator-hypervisor-driver-for-amd-processors#28]
Hi,

I'm getting these errors when trying to install the emulator from a system administrator cmd

![imagen](https://user-images.githubusercontent.com/2971107/89381574-b16af900-d6f9-11ea-95ad-f6c48d707232.png)

Here is the info of my CPU

![imagen](https://user-images.githubusercontent.com/2971107/89381596-b9c33400-d6f9-11ea-9965-a48dcb36cbd0.png)

**Comment by denislfernandez** [comment]
Hi again,

After getting the previous error trying to install the 1.6.0 version of the driver I went to the Android Studio AVD Manager to launch the emulator and prompted me to install the hypervisor driver and installed successfully the version 1.5.0

![imagen](https://user-images.githubusercontent.com/2971107/89382215-c4ca9400-d6fa-11ea-8e94-b82741fd216b.png)

Just letting you now in case this is relevant

**Comment by Taogle2018** [comment]
This is strange as installing 1.6 should be the same as installing 1.5.
The error code seems to suggest that driver is in use when trying to installing 1.6. Is this true?
Stop any emulator should solve the issue. Or in case there is weird error in the Windows, I suppose a reboot can fix the problem.

**Comment by denislfernandez** [comment]
Hi again,

You're totally right. I've just updated to 1.6 without any problem. I've must have tried to update to 1.6 without realising that the emulator was running on the background. Sorry for all the trouble!
