### ISSUE TITLE
win10 2004,Android Studio4.0.1，Your CPU does not support required features (VT-x or SVM).

### ISSUE THREAD

**Issue by GaoYingjie1995** [google/android-emulator-hypervisor-driver-for-amd-processors#29]
My CPU is amd R5 2400g, which supports SVM, but the prompt does not
![Snipaste_2020-08-06_20-13-32](https://user-images.githubusercontent.com/37998857/89531056-29344300-d822-11ea-8a94-0412bf58462c.png)
![Snipaste_2020-08-06_20-15-26](https://user-images.githubusercontent.com/37998857/89531098-3f420380-d822-11ea-9c62-ecf6ad1a5578.png)
![Snipaste_2020-08-06_20-15-49](https://user-images.githubusercontent.com/37998857/89531116-46691180-d822-11ea-9aec-06e42a7df2cd.png)

**Comment by fusionneur** [comment]
Which is the output of 
``emulator-check.exe cpu-info``

**Comment by Taogle2018** [comment]
Hello, are you able to download the driver release here from github and run the installer script? This will help me identify whether "Android Studio" itself is working?
你好，你可以试试下载github的驱动安装包，手工安装一下?

**Comment by GaoYingjie1995** [comment]
> Which is the output of
> `emulator-check.exe cpu-info`

![Snipaste_2020-08-07_09-19-20](https://user-images.githubusercontent.com/37998857/89598405-510dc000-d88f-11ea-90ab-c1349e85c4b2.png)

**Comment by GaoYingjie1995** [comment]
> Hello, are you able to download the driver release here from github and run the installer script? This will help me identify whether "Android Studio" itself is working?
> 你好，你可以试试下载github的驱动安装包，手工安装一下?

I tried it. I downloaded the 1.6 version, and I ran silent_install_safe.bat as an administrator, and the installation failed. I ran silent_install.bat, the screen flashed and it closed
![Snipaste_2020-08-07_09-27-16](https://user-images.githubusercontent.com/37998857/89598904-9ed6f800-d890-11ea-81df-37b39db2521a.png)

**Comment by GaoYingjie1995** [comment]
I tried it. I downloaded the 1.6 version, and I ran silent_install_safe.bat as an administrator, and the installation failed. I ran silent_install.bat, the screen flashed and it closed





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/android-emulator-hypervisor-driver-for-amd-processors"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 凌晨1:23
收件人:&nbsp;"google/android-emulator-hypervisor-driver-for-amd-processors"<android-emulator-hypervisor-driver-for-amd-processors@noreply.github.com&gt;;
抄送:&nbsp;"高英杰"<gaoyingjiectt@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [google/android-emulator-hypervisor-driver-for-amd-processors] win10 2004,Android Studio4.0.1，Your CPU does not support required features (VT-x or SVM). (#29)





 
Hello, are you able to download the driver release here from github and run the installer script? This will help me identify whether "Android Studio" itself is working?
 你好，你可以试试下载github的驱动安装包，手工安装一下?

**Comment by GaoYingjie1995** [comment]
> Hello, are you able to download the driver release here from github and run the installer script? This will help me identify whether "Android Studio" itself is working?
> 你好，你可以试试下载github的驱动安装包，手工安装一下?

![Snipaste_2020-08-07_10-02-11](https://user-images.githubusercontent.com/37998857/89600735-5241eb80-d895-11ea-9a49-a7d1f88231e1.png)
![Snipaste_2020-08-07_10-01-41](https://user-images.githubusercontent.com/37998857/89600749-579f3600-d895-11ea-8ddd-e916278b1bfd.png)

**Comment by Taogle2018** [comment]
你可以不理会这个错误，创建一个avd，然后在命令行试试看，能不能用。
最好试一下emulator.exe -accel-check先，看截图是安装成功了。

**Comment by GaoYingjie1995** [comment]
> 你可以不理会这个错误，创建一个avd，然后在命令行试试看，能不能用。
> 最好试一下emulator.exe -accel-check先，看截图是安装成功了。

还是不行 启动不了
![Snipaste_2020-08-07_13-13-56](https://user-images.githubusercontent.com/37998857/89611911-f84f1f00-d8b0-11ea-9618-c00e93b5d968.png)

**Comment by Taogle2018** [comment]
看起来像是你的emulator是很老的版本，否则不应该是这样的信息才对。你这个是最新的吗？

**Comment by GaoYingjie1995** [comment]
> 看起来像是你的emulator是很老的版本，否则不应该是这样的信息才对。你这个是最新的吗？

非常感谢你的帮助，升级emulator失败后重新卸载安装最新版emulator解决。可以在Android Studio中正常使用。感谢

**Comment by Taogle2018** [comment]
不用谢，能用就好。
