### ISSUE TITLE
Android emulator hypervisor fails to install !!

### ISSUE THREAD

**Issue by arixank** [google/android-emulator-hypervisor-driver-for-amd-processors#31]
I have tried everything to get the thing installed but in vain !! Also each time it gives me an error while installing , I have also enabled Virtualization , hyper-v is not found on windows feature !!! And the powershell thing also doesn't work as hyper-v is not enabled on my Windows - 10 home edition !! Also I had disabled the antivirus and also turned off antivirus virtualization (antivirus : AVAST) !!
I want to use this emulator for flutter development !! Really fed up of trying to get this thing running !!

I have also attached the screen shots !!! So please help me with it !!
Laptop Details :
Asus - X542BA
Ram : 4GB
Processor : AMD A6
Android Studio version: 4.0.1

![Screenshot (1035)](https://user-images.githubusercontent.com/50585400/90949999-4d6f6100-e46b-11ea-8708-6f0bd337d240.png)

![Screenshot (1036)](https://user-images.githubusercontent.com/50585400/90950007-56603280-e46b-11ea-9839-6d336a378664.png)

![Screenshot (1038)](https://user-images.githubusercontent.com/50585400/90950012-6415b800-e46b-11ea-96ee-1cff9f81cdcf.png)

![Screenshot (1040)](https://user-images.githubusercontent.com/50585400/90950038-a939ea00-e46b-11ea-8ecb-f7691060f7de.png)

**Comment by zombodotcom** [comment]
this might not be the solution. 

I have hyper-V enabled on an AMD 3700x..

and my friend cant run it with his amd system

![image](https://user-images.githubusercontent.com/13477955/90994716-e5a63c80-e576-11ea-81d8-2d5f70ff2d86.png)

**Comment by arixank** [comment]
> this might not be the solution. 
> 
> I have hyper-V enabled on an AMD 3700x..
> 
> and my friend cant run it with his amd system
> 
> ![image](https://user-images.githubusercontent.com/13477955/90994716-e5a63c80-e576-11ea-81d8-2d5f70ff2d86.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/13477955/90994755-05d5fb80-e577-11ea-8dd5-409695a249c6.png)
> 

Buddy you will have to disable hyper-v first!

**Comment by arixank** [comment]
> this might not be the solution. 
> 
> I have hyper-V enabled on an AMD 3700x..
> 
> and my friend cant run it with his amd system
> 
> ![image](https://user-images.githubusercontent.com/13477955/90994716-e5a63c80-e576-11ea-81d8-2d5f70ff2d86.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/13477955/90994755-05d5fb80-e577-11ea-8dd5-409695a249c6.png)
> 

Of course it may not work for everyone!! As the previous solutions from other thread didn't work for me!!it's a part of dev's life

**Comment by AkkiBB** [comment]
Hello! I think I've followed the steps you detailed and at the point where I need to run the "emulator-check.exe hyper-v" command, it's not recognized. Where did I mess up?
![image](https://user-images.githubusercontent.com/32875894/91285294-b6214b00-e795-11ea-9c48-15fe1fd93a12.png)

**Comment by JJ36CF** [comment]
> at the point where I need to run the "emulator-check.exe hyper-v" command, it's not recognized. Where did I mess up?
> ![image](https://user-images.githubusercontent.com/32875894/91285294-b6214b00-e795-11ea-9c48-15fe1fd93a12.png)

You're running the command from the wrong location. emulator-check.exe is located in **...\Android\Sdk\emulator**.

> The "bcdedit /set hypervisorlaunchtype off" command doesn't work either.
> ![image](https://user-images.githubusercontent.com/32875894/91288285-7d837080-e799-11ea-905a-94087611c1c9.png)

You need to run the command prompt as administrator. That's why it's telling you that "Access is denied."

**Comment by AkkiBB** [comment]
Oh.. Well that's embarrassing haha. That fixed it for me thank you very much!

**Comment by arixank** [comment]
> @AkkiBB
> > at the point where I need to run the "emulator-check.exe hyper-v" command, it's not recognized. Where did I mess up?
> > ![image](https://user-images.githubusercontent.com/32875894/91285294-b6214b00-e795-11ea-9c48-15fe1fd93a12.png)
> 
> You're running the command from the wrong location. emulator-check.exe is located in **...\Android\Sdk\emulator**.
> 
> > The "bcdedit /set hypervisorlaunchtype off" command doesn't work either.
> > ![image](https://user-images.githubusercontent.com/32875894/91288285-7d837080-e799-11ea-905a-94087611c1c9.png)
> 
> You need to run the command prompt as administrator. That's why it's telling you that "Access is denied."
> 
> 
> 

He's right!

**Comment by Liinadec** [comment]
> oooooffff!!
> Finally I fixed it by myself , so here's what I did to solve my problem!!
> 
> Type the following:
> In your shell : systeminfo (refer the attached image)
> 
> I'm using Windows 10 Home edition , which by default doesn't ship with Hyper-v thing !! So I used an external bat file to install !! [File is attached , make sure you run it as administrator( FILENAME: "Hyper-V-enabler.bat" , make sure you unzip it !!) ] , wait before you do that check weather your system has required configs (modern system meets the requirements by default)
> 
> After installing and restarting the computer , now you should be able to see the hyper - v in your windows features box !!
> 
> Simply uncheck it !! (Ya it's a bit stupid , but have too...!!) and restart !!
> 
> Now , navigate to programfiles/android/sdk/emulators : or where ever you have installed your sdk !!
> In the top search bar , enter cmd and open the cmd in your current directory !!
> and type :
> emulator-check.exe hyper-v
> 
> if it displays hyper-v:disabled then you are good to go !!
> You can disable hyper-v through powershell as mentioned in official Microsoft support page !! But that didn't work for me !!
> So , open a cmd as administrator and type the following command :
> bcdedit /set hypervisorlaunchtype off
> 
> execute and the restart !! [last restart]
> 
> Now , you can install amd hypervisor blah blah baa and be happy at last !!!
> Make sure you get a success after the driver installation !!
> 
> ![Annotation 2020-08-22 163518](https://user-images.githubusercontent.com/50585400/90954945-bfa96b00-e496-11ea-8ab5-1ff34cb45d00.png)
> [Hyper-V-Enabler.zip](https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors/files/5112280/Hyper-V-Enabler.zip)



> > возможно, это и не решение проблемы.
> > У меня включен hyper-V на AMD 3700x..
> > и мой друг не может запустить его со своей системой amd
> > ![изображение](https://user-images.githubusercontent.com/13477955/90994716-e5a63c80-e576-11ea-81d8-2d5f70ff2d86.png)
> > ![изображение](https://user-images.githubusercontent.com/13477955/90994755-05d5fb80-e577-11ea-8dd5-409695a249c6.png)
> 
> Of course it may not work for everyone!! As the previous solutions from other thread didn't work for me!!it's a part of dev's life

Words cannot convey how grateful I am to you, sir, virtualization just stopped working on my laptop, and thanks to your installer everything worked after a week, good luck and success in your endeavors!

**Comment by anonym24** [comment]
**Hyper-V** has nothing to do with **Android Emulator hypervisor driver** (AEHD).

To check if AEHD is installed and running:

```
SERVICE_NAME: aehd
       ...
       STATE              : 4  RUNNING
       ...
```

If it's not running:

```
SERVICE_NAME: aehd
       ...
       STATE              : 1  STOPPED
       WIN32_EXIT_CODE    : 4294967201 (0xffffffa1)
       ...
```

then `The following error message means either that virtualization extension is not enabled in your BIOS or that Hyper-V is not disabled`

So actually, you have to keep **Hyper-V** disabled to make **AEHD** work but instead you have enabled it.

https://developer.android.com/studio/run/emulator-acceleration#vm-windows

[Hyper-V must be disabled to use the Android Emulator hypervisor driver or Intel HAXM](https://developer.android.com/studio/run/emulator-acceleration#disable-hyper-v)
