### ISSUE TITLE
WARNING: Host CPU is missing the following feature(s) required for x86 emulation: SSSE3

### ISSUE THREAD

**Issue by JJ36CF** [google/android-emulator-hypervisor-driver-for-amd-processors#32]
Hi,
I've finally managed to install the hypervisor driver but when I try to launch an AVD in the emulator I get several warnings, one of them being that my CPU is lacking the SSSE3 feature. The emulator screen remains black and eventually the AVD Manager tells me: `Timed out after 300seconds waiting for emulator to come online`.

---

I'm really confused about the SSSE3 warning because I'm running Windows and, according to the user guide [Run apps on the Android Emulator](https://developer.android.com/studio/run/emulator), SSSE3 is only required for Linux users:
>The use of hardware acceleration has additional requirements on Windows and Linux:
>
>* Intel processor on Windows or Linux: Intel processor with support for Intel VT-x, Intel EM64T (Intel 64), and Execute Disable (XD) Bit functionality
>* AMD processor on Linux: AMD processor with support for AMD Virtualization (AMD-V) and Supplemental Streaming SIMD Extensions 3 (SSSE3)
>* AMD processor on Windows: Android Studio 3.2 or higher and Windows 10 April 2018 release or higher for Windows Hypervisor Platform (WHPX) functionality

(https://developer.android.com/studio/run/emulator#requirements)

---

I followed the directions in the user guide [Configure hardware acceleration for the Android Emulator](https://developer.android.com/studio/run/emulator-acceleration) and made sure my PC met all the requirements stated there as well:

>* AMD processor with Secure Virtual Machine (SVM) Technology
>* 64-bit Windows 10, Windows 8, or Windows 7 (32-bit Windows is not supported)
>* To use Android Emulator Hypervisor Driver for AMD Processors on Windows 10 or 8, you must turn off Hyper-V in the Windows Feaures Dialog.
**Note**: Installing certain software might turn Hyper-V back on. Refer to Disabling Hyper-V for more details.

(https://developer.android.com/studio/run/emulator-acceleration#vm-windows-aehdamd)

---

So, is SSSE3 required for Windows users after all? Is the user guide just incorrect or am I missing something? 🤔 This is getting really frustrating. 😞

Please help me get the emulator up and running. Thank you!

## PC Configuration:
**CPU**: AMD Phenom II X6 1090t (which has SVM but **not** SSSE3)
**OS:** Windows 10 Education 64-bit, version 1909
**Android Studio version:** 4.0.1

I have **uninstalled Hyper-V** and **SVM mode is activated** in my BIOS.

## Full Event Log:
```
15:46	Emulator: Warning: Quick Boot / Snapshots not supported on this machine. A CPU with EPT + UG features is currently needed. We will address this in a future release.

15:46	Emulator: emulator: WARNING: Host CPU is missing the following feature(s) required for x86 emulation: SSSE3

15:46	Emulator: Hardware-accelerated emulation may not work properly!

15:47	Emulator: dsound: Could not initialize DirectSoundCapture

15:47	Emulator: dsound: Reason: No sound driver is available for use, or the given GUID is not a valid DirectSound device ID

15:47	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

15:47	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

15:47	Emulator: audio: Failed to create voice `goldfish_audio_in'

15:47	Emulator: D:\Programs\Android_SDK\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: warning: opening audio input failed

15:47	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

15:47	Emulator: dsound: Attempt to initialize voice without DirectSoundCapture object

15:47	Emulator: audio: Failed to create voice `adc'
```

**Comment by Taogle2018** [comment]
Sorry for the problem of online document. Let me clarify this:
Actually SSSE3 is required.
1> It is required for both Intel and AMD. However, Intel usually has it.
2> It is required for Linux/Windows. Actually, required for mac as well. But mac is always Intel. Refer to 1>.
3> It is required by Android OS on x86 itself not by emulator itself.

**Comment by JJ36CF** [comment]
Hi @Taogle2018 ,
Thank you very much for clarifying!
> 3> It is required by Android OS on x86 itself not by emulator itself.

So if I understand you correctly, SSSE3 is **always required**. Using WHPX rather than the Android Emulator Hypervisor Driver for AMD Processors won't work either and I will definitely need to upgrade my CPU to get hardware acceleration. Is that right?

**Comment by Taogle2018** [comment]
Right! There is a very small possibility that a hypervisor might be able to use software to emulate these instructions. However, I don't really see one. Hyper-V is a black box. You can have a try at least and see if it does provide such support.
