### ISSUE TITLE
Android Emulator Hypervisor Driver for AMD Processors installation failed

### ISSUE THREAD

**Issue by minikupa** [google/android-emulator-hypervisor-driver-for-amd-processors#33]
[SC] ControlService 실패 1062:

서비스가 시작되지 않았습니다.

[SC] DeleteService 성공
[SC] 4294967201 오류가 발생하여 StartService이(가) 실패했습니다.
Android Emulator Hypervisor Driver for AMD Processors installation failed. To install Android Emulator Hypervisor Driver for AMD Processors follow the instructions found at: https://github.com/google/android-emulator-hypervisor-driver-for-amd-processors

I enable SVM, disable hyper-v
![주석 2020-08-29 192815](https://user-images.githubusercontent.com/19676242/91634831-6610e580-ea2e-11ea-9af8-c35b525f317b.jpg)
사용 is enable
![주석 2020-08-29 193224](https://user-images.githubusercontent.com/19676242/91634833-67421280-ea2e-11ea-90e0-cebdb66114c0.jpg)

**Comment by Taogle2018** [comment]
According to past experience, there are a few things need to check.
Can you share your CPU model? Screenshot of "emulator-check.exe hyper-v"? What is the antivirus program?
