### ISSUE TITLE
not able to install android emulator for amd

### ISSUE THREAD

**Issue by yuvraj23092001** [google/android-emulator-hypervisor-driver-for-amd-processors#35]
![problem](https://user-images.githubusercontent.com/54389501/92319274-ec7f8580-f033-11ea-83ef-6aa1b18da275.png)

![part](https://user-images.githubusercontent.com/54389501/92319279-f608ed80-f033-11ea-8dfd-86e3c2a8e419.png)
  
although "Windows Event Log" is running it showing control service failed 1062

**Comment by yuvraj23092001** [comment]
please tell me what is problem and its solution

**Comment by Taogle2018** [comment]
Did you turn on SVM in bios? And can you post the output of "emulator-check.exe hyper-v"?
