### ISSUE TITLE
IRQL_LESS_OR_NOT_EQUAL by gvm.sys when resuming from hibernation 

### ISSUE THREAD

**Issue by HubKing** [google/android-emulator-hypervisor-driver-for-amd-processors#4]
I put the computer to sleep with an AVD running last night. Then the computer probably went into hibernation. When I turned the computer on today, the computer showed blue screen of error after passing the POST screen. The error message was IRQL_LESS_OR_NOT_EQUAL and the driver was "gvm.sys". gvm.sys seems to be the file from AMD hypervisor. I installed 1.4 that came with Android Studio 3.6.1.

This is the first time I saw this, and I am not sure if this will be reproducible or not, so I cannot report it to the Issue Tracker. But I do have the MEMORY.DMP file (1.5GB -> 200MB when compressed), and may be this could help you to find any potential issue. But since the memory dump may contain my personal information, I do not want to post it here where everyone can access the file. I am not sure if you would want to investigate this or not, but if you would, please let me know any way to send the file to you privately. For example, I could compress the file with a password, and upload the file on a publicly accessible temporary file sharing site, and send the password privately. If you would not like to investigate this, please close this.

**Comment by Taogle2018** [comment]
Hello, thanks for sharing your experience. And yes, if I can have the crash dump, it would very helpful. Can you share with me? Or does 1.5 work better in this case?

**Comment by HubKing** [comment]
Well, that was two months ago, and since there was no reply, I deleted the file. And the same thing has not happened since then, so whatever the reason was, I think it is not that important.

**Comment by Taogle2018** [comment]
Sorry I did not pay attention to the time stamp. If this could ever happen again, please let me know, thanks!
