### ISSUE TITLE
How to use this with qemu ?

### ISSUE THREAD

**Issue by beppe9000** [google/android-emulator-hypervisor-driver-for-amd-processors#5]
I would like to accelerate an aosp iso for android x86

**Comment by Taogle2018** [comment]
QEMU patch is not ready yet. Adding support to QEMU is not a priority here. However, I do have a patched QEMU. I can share with you if you like. But it is not tested much.

**Comment by beppe9000** [comment]
That's fine. I can try it a little.

**Comment by Taogle2018** [comment]
OK. Let me share with you. 
But please do remember the QEMU is NOT a google supported work as this Android Emulator Hypervisor Driver. It is a work in my spare time and more for people who want to play with QEMU for fun.  :)

**Comment by Taogle2018** [comment]
- Download and install msys2 

- Start C:\msys64\mingw64.exe

- Updates (then close window and restart mingw64.exe): pacman -Syu

- Updates: pacman -Su

- Install basic packets: pacman -S base-devel mingw-w64-x86_64-toolchain git python

- Install QEMU specific packets: pacman -S mingw-w64-x86_64-glib2 mingw-w64-x86_64-gtk3 mingw-w64-x86_64-SDL2

- Get QEMU sources:

git clone git://github.com/qemu-gvm/qemu-gvm.git
cd qemu-gvm
git submodule update --init ui/keycodemapdb
git submodule update --init capstone
git submodule update --init dtc

- Build QEMU:

./configure --enable-gtk --enable-sdl --target-list=x86_64-softmmu --disable-werror --disable-capstone
make
Run in qemu/x86_64-softmmu ./qemu-system-x86_64 -L ./../pc-bios

**Comment by beppe9000** [comment]
Thanks I will try!

**Comment by Taogle2018** [comment]
Let me close this issue. I am waiting for beppe9000's feedback. Now at least I know thesword53 can run the patched QEMU.

**Comment by beppe9000** [comment]
I was unable to compile because of some msys errors... during package install and configure. I'm still waiting to try on another machine, but with covid is a bit difficult right now

**Comment by Taogle2018** [comment]
https://1drv.ms/u/s!AljlID0ntVyugeg-BN5EnNV7Y2U2Hw?e=p3v1Ix
This is the one I built yesterday.

**Comment by Taogle2018** [comment]
Or you can save the old one and rename to something else, in case you will need later to boot Windows 7 or 10. The old one is a UEFI bios. @thesword53 told me how bios matters. If you keep both, you are able to use "-bios xxxxx" to the command line.

**Comment by beppe9000** [comment]
Ok, I tried replacing the file and making a backup of the old one. Now I get a kernel panic... which is better than no output. 🤷 

![image](https://user-images.githubusercontent.com/6625123/84376395-5f1dc800-abe1-11ea-95f7-05e62f5e83f1.png)

**Comment by thesword53** [comment]
@beppe9000 Download the file [OVMF_CODE.fd](https://drive.google.com/file/d/1uiwkdTB_IVDVckkeQ4NA41QlhRp2PnqA/view?usp=sharing) and add "-bios /path/to/OVMF_CODE.fd" to command line.

**Comment by Taogle2018** [comment]
I was able to boot android-x86_64-9.0-r1.iso on my Ryzen 2700 and Intel i9. I would like to help but it seems I can not reproduce it. Actually I was able to run 9.0-r2 and 14.1 as well.
Perhaps your AMD FX CPU makes difference here? Did you ever try to run the livecd directly on the hardware?

**Comment by beppe9000** [comment]
> add "-bios /path/to/OVMF_CODE.fd" to command line.
i tried this but it keeps rebooting after selecting the livecd option

> 
> I was able to boot android-x86_64-9.0-r1.iso on my Ryzen 2700 and Intel i9. I would like to help but it seems I can not reproduce it. Actually I was able to run 9.0-r2 and 14.1 as well.
> Perhaps your AMD FX CPU makes difference here? Did you ever try to run the livecd directly on the hardware?

i am going to try booting that iso from a usb key to check it for sure
