### ISSUE TITLE
support for AMD FX8320e ?

### ISSUE THREAD

**Issue by beppe9000** [google/android-emulator-hypervisor-driver-for-amd-processors#6]
Is this cpu supported, can support be added if not? How to run android virtual device with this?

**Comment by Taogle2018** [comment]
Sorry I do not know the answer indeed. Technically, if the CPU is supported by KVM, it should be supported here. However, I do not have the AMD CPUs other than Ryzen at hand. 
Did you run into problem with this CPU?

**Comment by beppe9000** [comment]
I was able to install the hypervisor driver following [this](https://androidstudio.googleblog.com/2019/10/android-emulator-hypervisor-driver-for.html) but I'm not sure how to get the emulator to use it.

![image](https://user-images.githubusercontent.com/6625123/81503259-e6c29f00-92e2-11ea-9782-378ec0a48efa.png)

**Comment by Taogle2018** [comment]
Version of your Android Studio and Android Emulator? It looks like old version.
Are you able to run the emulator from commandline? "emulator.exe -avd 2.7_QVGA_API_29 -verbose -show-kernel"

**Comment by beppe9000** [comment]
I checked it was 3.5.2 I'm now in the process of updating to try again.

**Comment by Taogle2018** [comment]
Regarding Android Studio's support for this, it is complicated. 4.0 Canary 5+ should be good. Old Android Studio does not accept changes like this any more. So, it is better to update to the latest emulator and use it in command line. In this case, android emulator is more like a standalone program without too much dependence on Android Studio.

**Comment by beppe9000** [comment]
it worked! the first vm started right without the haxm error.
![image](https://user-images.githubusercontent.com/6625123/81729937-16ada600-948d-11ea-958b-3d87d3918689.png)
