### ISSUE TITLE
Will there be an option to get this working with Hyper-v enabled?

### ISSUE THREAD

**Issue by cesarvarela** [google/android-emulator-hypervisor-driver-for-amd-processors#62]
Disabling means no WSL, less security, etc., not really a solution in the long term.

**Comment by davidgiga1993** [comment]
I fully agree with this! Hyper-V is here to stay and I can only imagine it will be integrated more and more into future windows features. Also not being able to use WSL is a no-go for me.
But in case you didn't know: You can still use the `WHPX` hypervisor as an alternative, see https://developer.android.com/studio/run/emulator-acceleration#vm-windows for details

**Comment by daryljodanny** [comment]
When using WHPX, the UI animations inside the emulator is choppy

**Comment by H4M5TER** [comment]
According to [here](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration), you're already using WHPX with Hyper-V enabled. (and correct Android SDK & Android Emulator version)

**Comment by uselessscat** [comment]
Maybe this helps https://stackoverflow.com/a/68286248/6658955

**Comment by grad1e** [comment]
> Maybe this helps https://stackoverflow.com/a/68286248/6658955

Came across that, but the issues which the user has described are needed all the time while I develop.

**Comment by Taogle2018** [comment]
No. This driver cannot co-exist with Hyper-V. Hyper-V is designed in a way no other hypervisor could work side by side.
Either use this driver with WSL v1 or use WHPX (which is another hyper-V wrapper) and WSL v2.
