### ISSUE TITLE
Can Android Emulator and WSL2 co-exist in Windows 10 Pro with Ryzen 7 CPU

### ISSUE THREAD

**Issue by zeroarst** [google/android-emulator-hypervisor-driver-for-amd-processors#68]
I searched answers around but I am still not sure if both can exist together? I have seen some threads said there is a bug that Google is working on fixing it https://issuetracker.google.com/issues/202188690?pli=1. But title says Windows 11. I am wondering if this case applies to Windows 10 as well? I can install Android Emulator drive by disabling Hyper-v and running `bcdedit /set hypervisorlaunchtype off`. But I am not able to use WSL2.

Dose anyone know that if both can be run together? Or just me did something wrong?

**Comment by Calabree** [comment]
As of currently there is no way to run both. The closest experience you can get is using WSA with WSL2, though things like reload do not work and it can be a bit annoying having to adb connect each session.

**Comment by Taogle2018** [comment]
Android Emulator and WSL2 can co-exist in Windows 10/Windows 11. However, in this config, virtualization engines for both are provided by Microsoft. The issue mentioned above was a bug of Microsoft virtualization.
However, Android Emulator Hypervisor Driver for AMD Processors does NOT co-exist with WSL2.
